[functions.mercado-pago-webhook]
verify_jwt = false

[functions.mercado-pago-checkout]
verify_jwt = true

[functions.gmail-sync]
verify_jwt = true

[functions.sat-descarga-masiva]
verify_jwt = true

[functions.mercado-pago-sync]
verify_jwt = true

[functions.manychat-api]
verify_jwt = true

[functions.imss-movement-submit]
verify_jwt = true

[functions.woocommerce-fetch-orders]
verify_jwt = true

[functions.woocommerce-process-test-order]
verify_jwt = true

[functions.exchange-rate]
verify_jwt = true

[functions.send-order-email]
verify_jwt = true

[functions.send-signup-notification]
verify_jwt = true

[functions.create-auth-user]
verify_jwt = true

[functions.create-payment-intent]
verify_jwt = true

[functions.delete-auth-user]
verify_jwt = true

[functions.delete-own-account]
verify_jwt = true

[functions.delivery-tracking-proxy]
verify_jwt = true

[functions.facturama-download]
verify_jwt = true

[functions.gmail-oauth-callback]
verify_jwt = true

[functions.paypal-webhook]
verify_jwt = false

[functions.reset-auth-user-password]
verify_jwt = true

[functions.send-verification-email]
verify_jwt = true

[functions.send-password-reset]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.woocommerce-webhook]
verify_jwt = false
