/*
  # Seed editable texts for the order page module

  Merges the default order-page texts and visibility toggles into the existing
  CustomerOrder CMS module content. Existing keys are preserved.
*/
UPDATE cms_modules
SET content = '{"stepLabelDuration":"Duración","stepLabelWeek":"Semana","stepLabelPlan":"Plan","stepLabelMenu":"Menú","stepLabelSummary":"Resumen","backButton":"Atrás","continueButton":"Continuar","nextWeekButton":"Siguiente semana","viewSummaryButton":"Ver resumen","durationTitle":"Duración del Plan","durationSubtitle":"Selecciona cuántas semanas deseas ordenar","duration1Label":"1 Semana","duration1Description":"Plan semanal","duration2Label":"2 Semanas","duration2Description":"Plan quincenal","duration4Label":"4 Semanas","duration4Description":"Plan mensual","durationNote":"Las semanas disponibles se seleccionarán automáticamente.","weeksTitle":"Semanas Seleccionadas","weeksSubtitle":"Haz clic en una semana para ver el menú","deliveryDateLabel":"Fecha de entrega","sundayDeliveryHours":"Entregas de 6:30 a 9:30 PM del domingo","mondayDeliveryHours":"Entregas en lunes a partir de las 10:00 AM","switchToMondayLabel":"Solicitar entrega en lunes","switchToSundayLabel":"Cambiar a entrega en domingo","familyTitle":"¿Para quién es este pedido?","familySubtitle":"Selecciona el miembro de la familia","familyRestrictionsNote":"El menú se filtrará automáticamente según estas restricciones","nextStepNotice":"El siguiente paso es seleccionar un plan para la semana con entrega el","planTitle":"Selecciona tu Plan","planCardHint":"Selecciona tus comidas favoritas del menú semanal","menuTitle":"Selecciona tu Menú","breakfastDescription":"Empieza el día con energía","lunchDescription":"El plato fuerte del día","dinnerDescription":"Cierra el día bien nutrido","minMealsTitle":"Completa el mínimo de comidas por semana","minMealsDescription":"Cada semana debe tener al menos 3 comidas principales (Desayuno, Comida o Cena). Las colaciones no cuentan para el mínimo.","colacionesTitle":"Completa las colaciones requeridas","colacionesDescription":"Los planes Fitness y Balance incluyen colaciones. Debes seleccionar el número requerido según tus comidas principales.","summaryTitle":"Resumen del Pedido","deliveryOptionRequired":"Selecciona una opción de entrega para continuar","loginPrompt":"Inicia sesion para agregar al carrito","loginButton":"Iniciar Sesion","signupButton":"Crear Cuenta","showMondayDelivery":true,"showNextStepNotice":true,"showMinMealsNotice":true,"showColacionesNotice":true}'::jsonb || COALESCE(content, '{}'::jsonb)
WHERE type = 'CustomerOrder';
